agent_settings:
  model: "gemini-2.0-flash"
  # model: "gemini-2.0-flash-live-001"
  # For audio streaming, we need a model that supports the Gemini Live API
  streaming_model: "gemini-2.0-flash-live-001"

# DevOps tool configurations will be added here as we implement them
devops_settings:
  # Placeholder for CI/CD settings
  cicd:
    # Example for Jenkins
    # jenkins_url: "http://your-jenkins-url"
    # jenkins_username: "your-username"
    # jenkins_api_token: "your-api-token"
    
    # Example for GitHub Actions
    # github_token: "your-github-token"
  
  # Placeholder for infrastructure settings
  infrastructure:
    # Example for Terraform
    # terraform_path: "/usr/local/bin/terraform"
    
    # Example for cloud providers
    # aws_access_key_id: "your-aws-access-key"
    # aws_secret_access_key: "your-aws-secret-key"
    # gcp_service_account_key: "path/to/service-account-key.json"
    # azure_subscription_id: "your-azure-subscription-id"
  
  # Placeholder for monitoring settings
  monitoring:
    # Example for Prometheus/Thanos
    thanos_url: "https://thanos-querier-openshift-monitoring.apps.ocp4.imss.work"
    thanos_token: "sha256~R8OUMMtj9dGBrvFyx1jtMr4oXobwMgCHBppyobJ8xG0"  # Use token for authentication
    ssl_verify: false  # Set to true if using valid SSL certificates
    timeout: 30
    
    # Example for Grafana
    # grafana_url: "http://your-grafana-url"
    # grafana_api_key: "your-grafana-api-key"
  
  # Kubernetes settings
  kubernetes:
    # Cluster connection settings
    api_url: "https://api.ocp4.imss.work:6443"
    username: "ocpadmin"
    password: "oShift@123"
    token: "sha256~R8OUMMtj9dGBrvFyx1jtMr4oXobwMgCHBppyobJ8xG0"  # Use token instead of username/password if preferred
    kubeconfig_path: "~/.kube/config"
    # For OpenShift clusters, you might need:
    # openshift_api_url: "https://api.your-cluster.example.com:6443"
    
  # Placeholder for deployment settings
  deployment:
    # Example for Kubernetes
    # kubeconfig_path: "~/.kube/config"
    
    # Example for Docker
    # docker_host: "unix:///var/run/docker.sock"

# Elasticsearch settings for log analysis
elasticsearch_settings:
  # Default connection settings (can be overridden by environment variables in MCP server)
  url: "https://172.16.3.63:9200"
  username: "elastic"
  password: "hlLWmR*tnDVMKkvR80ws"
  # For SSL connections, you might need:
  ssl_skip_verify: true
  
  # Additional settings for the Elasticsearch agent
  default_index_pattern: "logs-*"
  max_results: 1000
  timeout: 30